PERMISSIONS: list[tuple[str, str, str]] = [
    ("crm.read", "crm", "View CRM"),
    ("crm.write", "crm", "Manage CRM"),
    ("projects.read", "projects", "View projects"),
    ("projects.write", "projects", "Manage projects"),
    ("shoots.read", "production", "View shoots"),
    ("shoots.write", "production", "Manage shoots"),
    ("tasks.read", "tasks", "View tasks"),
    ("tasks.write", "tasks", "Manage tasks"),
    ("assets.read", "assets", "View assets"),
    ("assets.write", "assets", "Manage assets"),
    ("assets.approve", "assets", "Approve assets"),
    ("quotes.read", "finance", "View quotes"),
    ("quotes.write", "finance", "Manage quotes"),
    ("invoices.read", "finance", "View invoices"),
    ("invoices.write", "finance", "Manage invoices"),
    ("payments.write", "finance", "Record payments"),
    ("expenses.write", "finance", "Manage expenses"),
    ("finance.read", "finance", "View financial summaries"),
    ("marketing.read", "marketing", "View marketing"),
    ("marketing.write", "marketing", "Manage marketing"),
    ("seo.read", "seo", "View SEO"),
    ("seo.write", "seo", "Manage SEO"),
    ("analytics.read", "analytics", "View analytics"),
    ("calendar.read", "calendar", "View calendar"),
    ("calendar.write", "calendar", "Manage calendar"),
    ("team.read", "team", "View team"),
    ("team.write", "team", "Manage team"),
    ("team.invite", "team", "Invite users"),
    ("org.write", "org", "Edit organization"),
    ("audit.read", "audit", "View audit logs"),
    ("automation.read", "automation", "View automation"),
    ("automation.write", "automation", "Manage automation"),
    ("notes.write", "collab", "Write notes"),
]

ROLE_KEYS = [
    "admin",
    "production_manager",
    "marketer",
    "seo_specialist",
    "accountant",
    "team_member",
    "client",
]

ROLE_PERMISSIONS: dict[str, list[str]] = {
    "admin": [p[0] for p in PERMISSIONS],
    "production_manager": [
        "crm.read",
        "crm.write",
        "projects.read",
        "projects.write",
        "shoots.read",
        "shoots.write",
        "tasks.read",
        "tasks.write",
        "assets.read",
        "assets.write",
        "calendar.read",
        "calendar.write",
        "quotes.read",
        "invoices.read",
        "finance.read",
        "analytics.read",
        "notes.write",
        "marketing.read",
        "seo.read",
        "team.read",
    ],
    "marketer": [
        "crm.read",
        "crm.write",
        "projects.read",
        "marketing.read",
        "marketing.write",
        "analytics.read",
        "tasks.read",
        "tasks.write",
        "calendar.read",
        "calendar.write",
        "notes.write",
        "seo.read",
        "finance.read",
    ],
    "seo_specialist": [
        "crm.read",
        "projects.read",
        "seo.read",
        "seo.write",
        "tasks.read",
        "tasks.write",
        "analytics.read",
        "calendar.read",
        "notes.write",
    ],
    "accountant": [
        "crm.read",
        "projects.read",
        "quotes.read",
        "quotes.write",
        "invoices.read",
        "invoices.write",
        "payments.write",
        "expenses.write",
        "finance.read",
        "analytics.read",
        "calendar.read",
        "notes.write",
    ],
    "team_member": [
        "projects.read",
        "shoots.read",
        "tasks.read",
        "tasks.write",
        "assets.read",
        "assets.write",
        "calendar.read",
        "notes.write",
    ],
    "client": [
        "projects.read",
        "assets.read",
        "assets.approve",
        "quotes.read",
        "invoices.read",
        "calendar.read",
        "notes.write",
    ],
}
